# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.1.0"
    hooks:
    -   id: no-commit-to-branch
        args: ["--branch", "master", "--branch", "main"]
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        args: ["--maxkb", "86000"]

-   repo: https://github.com/pycqa/isort
    rev: "5.10.1"
    hooks:
    - id: isort
      types: [python]
      args: ["--profile", "black"]

-   repo: https://github.com/psf/black
    rev: "22.3.0"
    hooks:
    -   id: black

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.942"
    hooks:
    -   id: mypy
        additional_dependencies: [numpy, pydantic, types-PyYAML, types-python-dateutil, types-requests]

-   repo: https://github.com/PyCQA/flake8
    rev: "4.0.1"
    hooks:
    -   id: flake8
        types: [python]

-   repo: https://github.com/PyCQA/pydocstyle
    rev: '6.1.1'
    hooks:
    -   id: pydocstyle
        types: [python]
        files: "breezy/.*"
        args: ["--convention", "google", "--add-ignore", "D301"]
        additional_dependencies: [toml]

-   repo: https://github.com/nbQA-dev/nbQA
    rev: "1.3.1"
    hooks:
    -   id: nbqa-isort
        args: ["--profile=black"]
    -   id: nbqa-black
    -   id: nbqa-mypy
        # additional_dependencies: [numpy, pydantic, mypy, types-python-dateutil, types-PyYAML]
    -   id: nbqa-flake8
        args: ["--config=.flake8", "--extend-ignore=E402"]

-   repo: https://github.com/MarcoGorelli/check-execution-order
    rev: v0.1.1
    hooks:
    -   id: check-execution-order
